name: CI/CD to EKS (Backend + Frontend)

on:
  push:
    branches: [main]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout app repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set unique image tag (short commit SHA)
      - name: Set image tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Build & push backend
      - name: Build and Push backend image
        run: |
          docker build --no-cache -t ${{ secrets.ECR_BACKEND_URI }}:${{ env.IMAGE_TAG }} ./backend
          docker push ${{ secrets.ECR_BACKEND_URI }}:${{ env.IMAGE_TAG }}

      # Build & push frontend
      - name: Build and Push frontend image
        run: |
          docker build --no-cache -t ${{ secrets.ECR_FRONTEND_URI }}:${{ env.IMAGE_TAG }} ./frontend
          docker push ${{ secrets.ECR_FRONTEND_URI }}:${{ env.IMAGE_TAG }}

  update-helm-values:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Helm repo
        uses: actions/checkout@v3
        with:
          repository: azizarfaoui11/Homie-GitOps  
          token: ${{ secrets.PAT_TOKEN }} 
          ref: main

      - name: Update values.yaml with new image tags
        run: |
          sed -i "s|image:.*backend:.*|image: \"${{ secrets.ECR_BACKEND_URI }}:${{ env.IMAGE_TAG }}\"|" homie-chart/values.yaml
          sed -i "s|image:.*frontend:.*|image: \"${{ secrets.ECR_FRONTEND_URI }}:${{ env.IMAGE_TAG }}\"|" homie-chart/values.yaml


      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add homie-chart/values.yaml
          git commit -m "Update images to tag ${{ env.IMAGE_TAG }}"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/azizarfaoui11/Homie-GitOps.git
          git push origin main
